Rename osm_mysql to mysql_root
Port over autogeneration of config values from the vm charm

Autogenerate config values for the mysql legacy relation

Add upterm session to debug failing integration test

Always set up upterm session

Pass essential env with built charm to upterm session

Fix minor bugs + remove upterm github action step

Run format

[upload-charm-docs] Migrate charm docs (#266)

* 'modified: docs/explanation/e-flowcharts.md,docs/explanation/e-interfaces.md,docs/index.md,docs/how-to/h-enable-monitoring.md // new: docs/explanation/e-legacy-charm.md,docs/how-to/h-deploy-gke.md'

* 'modified: docs/explanation/e-legacy-charm.md,docs/index.md'

* 'modified: docs/how-to/h-deploy-gke.md'

---------

Co-authored-by: upload-charms-docs-bot <upload-charms-docs-bot@users.noreply.github.com>

DPE-2068 use kill-delay (#258)

* use kill-delay

* update requirements and delay time

DPE-2225 using allocable memory instead of `free` (#256)

* using allocable memory instead of `free`

* use loose opt modifier

* merged from vm

* remove comment

* fix memory units

* set missing trust and testing profile in test

* adjust for low memory

* test change for ci

* fix function call

* typing fixes

* test wait for maintenance of instance before asserting recovery

* extra wait step

* strip trailing newline

* non-active

Fixes for network partition test (#272)

* fixes for chaos-mesh

* ensure chaos-mesh availability before test
* fixes destroy script
* function scoped

* address pr comment

* fix call

Port peer juju secret implementation from the vm charm (#263)

Upgrade mysql (v0.38) and tls (v0.2) charm libs + minor adjustments

[MISC] Revert change on Discourse Sync action (#265)

Co-authored-by: upload-charms-docs-bot <upload-charms-docs-bot@users.noreply.github.com>

[upload-charm-docs] Migrate charm docs (#266)

* 'modified: docs/explanation/e-flowcharts.md,docs/explanation/e-interfaces.md,docs/index.md,docs/how-to/h-enable-monitoring.md // new: docs/explanation/e-legacy-charm.md,docs/how-to/h-deploy-gke.md'

* 'modified: docs/explanation/e-legacy-charm.md,docs/index.md'

* 'modified: docs/how-to/h-deploy-gke.md'

---------

Co-authored-by: upload-charms-docs-bot <upload-charms-docs-bot@users.noreply.github.com>

DPE-2068 use kill-delay (#258)

* use kill-delay

* update requirements and delay time

DPE-2225 using allocable memory instead of `free` (#256)

* using allocable memory instead of `free`

* use loose opt modifier

* merged from vm

* remove comment

* fix memory units

* set missing trust and testing profile in test

* adjust for low memory

* test change for ci

* fix function call

* typing fixes

* test wait for maintenance of instance before asserting recovery

* extra wait step

* strip trailing newline

* non-active

Pin python dependencies with Poetry (#273)

[MISC] Switch maintainers to the DPE mailing list (#269)

* Switch maintainers to the DPE mailing list

* Update metadata.yaml

Co-authored-by: Carl Csaposs <carl.csaposs@canonical.com>

---------

Co-authored-by: Carl Csaposs <carl.csaposs@canonical.com>

Pin charmcraft to 2.3.0 in release.yaml to fix build (#276)

charmcraft pinned to 2.3.0 in integration test build but not release build

https://github.com/canonical/charmcraft/issues/1179

Add missing group markers (#278)

Leftover from #273

No integration tests were running since no groups were collected

Address PR feedback

diff --git a/charmcraft.yaml b/charmcraft.yaml
--- a/charmcraft.yaml
+++ b/charmcraft.yaml
@@ -11,9 +11,17 @@ bases:
         channel: "22.04"
 parts:
   charm:
+    override-pull: |
+      craftctl default
+      if [[ ! -f requirements.txt ]]
+      then
+          echo 'ERROR: Use "tox run -e build" instead of calling "charmcraft pack" directly' >&2
+          exit 1
+      fi
     build-packages:
       - libffi-dev
       - libssl-dev
+      - pkg-config
       - rustc
       - cargo
 
